### ISSUE TITLE
using USRP receive packet in practical

### ISSUE THREAD

**Issue by jimmyweibg** [hui811116/gr-wifi-dsss#1]
Dear Huang Teng-Hui,  
     My name is Jimmy. I am the student who is studying in NTUST in Taiwan. We have used your 802.11b open source to do the project. But we have met some problems. 
     First, we can receive the packet in your open source(self-loop) in 1Mbps and 2Mbps in long preamble. But we can’t receive the packet in 5.5Mbps and 11Mbps. Whether you have received it successfully until now? 
     Second, if we use USRP receive packet in practical, we even can’t receive the packet in 1Mbps and 2Mbps. Whether your open source(self-loop) can work in practical? Please feel free to contact me if you need any further information. 

Thanking you so much for reading my letter.

Best regards, 
jimmy

**Comment by hui811116** [comment]
Hi jimmy,
Thank you for using this project.
1. For 5.5M and 11Mbps Chirp Spread Spectrum (CSS), they were not fully tested.
2. And if you would like to receive real world ieee 802.11 signals, the bandwidth for the USRP should be at least 20MHz (which means 40MHz sampling rate). The USRPs I used then were B210/N210 (probably outdated today) and they don't support such high sampling rate. So i am afraid that the source codes are not able to receive real world wifi signals.

Please feel free to contact me through emails or leave messages here if you would like to know more.

Best,
Teng-Hui

**Comment by jimmyweibg** [comment]
Dear Huang Teng-Hui,
     Thank you for your reply.  I have surfed the internet. However, it said the USRPs(B210/N210) can support at most 61.44MHz. So, I confuse why your USRPs can't support 802.11 bandwidth(40MHz sampling rate)? Please check the link that I surfed from the internet.

link : https://kb.ettus.com/About_USRP_Bandwidths_and_Sampling_Rates

Best regards,
jimmy

**Comment by hui811116** [comment]
Hi Jimmy,
Yes, you are right. However, in practice, we don't want to run on the limit (which will require sampling with sinc function). Instead, a common practice is to oversample the signals to ease the sampling process (samples per symbols>4, even, in other words, we need 80MHz with 4 oversample factor). 

Also, I think I should highlight that this prototype is not completely capable of receiving ieee802.11b signals.The main feature is a demonstration of the modulation as well as part of the channel coding. So again, if you plan to receive real ieee802.11b signals, you need to refer to the PHY of the standard document and modify the sampling part.

**Comment by CN-Movn** [comment]
Dear Huang Teng-Hui,
My name is Movn, I am a student in the Xidian University. Thanks for your sharing. But when I install your blocks and try to run the examples, I find that there is a block missed. I noticed that there are only three blocks installed and there is four C++ function in the "lib". How can I solve this problem?

Thank you so much for reading my letter.

Best regards,
Movn

**Comment by hui811116** [comment]
> Dear Huang Teng-Hui,
> My name is Movn, I am a student in the Xidian University. Thanks for your sharing. But when I install your blocks and try to run the examples, I find that there is a block missed. I noticed that there are only three blocks installed and there is four C++ function in the "lib". How can I solve this problem?
> 
> Thank you so much for reading my letter.
> 
> Best regards,
> Movn

Hi Movn,
I assume you are trying to use this along with USRP, then have you installed the gr-gadget, which is a prerequisite for this module? Thanks.

Best,
Teng-Hui

**Comment by CN-Movn** [comment]
Dear Huang Teng-Hui,
Thank you very much for your reply, especially since I did not expect your reply so quickly. I really didn't notice whether gr-gadget was installed, I will try it next. Thanks again for your help.


Best regards,
Movn
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hui811116/gr-wifi-dsss"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 晚上8:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hui811116/gr-wifi-dsss] using USRP receive packet in practical (#1)





  
Dear Huang Teng-Hui,
 My name is Movn, I am a student in the Xidian University. Thanks for your sharing. But when I install your blocks and try to run the examples, I find that there is a block missed. I noticed that there are only three blocks installed and there is four C++ function in the "lib". How can I solve this problem?
 
Thank you so much for reading my letter.
 
Best regards,
 Movn
  
Hi Movn,
 I assume you are trying to use this along with USRP, then have you installed the gr-gadget, which is a prerequisite for this module? Thanks.
 
Best,
 Teng-Hui
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
